### PR TITLE
MERGING develop into release/24.10

### PR DESCRIPTION
**Pull request by delcroip**
MERGING develop into release/24.10

### CODE REVIEW

**Comment by delcroip** [comment]
@sniedzielski what should we do for the lint issues?

**Comment by sniedzielski** [comment]
Let's fix them. Someone from our team can fix this automatically in for example Visual Studio Code if the plugin for 'eslint' is installed. My fault here - I have new computer and I haven't installed this plugin yet therefore there are this 'issues;.

**Comment by sniedzielski** [comment]
@delcroip eslint fixed

**Comment by sniedzielski** [comment]
@delcroip eslint is fixed

**Pull request merged**
